language: cpp

addons:
    apt:
        packages:
            - bsdtar
            - libdbus-1-dev
            - autoconf-archive
            - libreadline-dev
            - libtool
            - autoconf-archive

sudo: required

os:
    - linux
    - osx

compiler:
    - gcc
    - clang

before_install:
    - .travis/before_install.sh

script:
    - .travis/script.sh

after_success:
    - ssh-agent .travis/after_success.sh

env:
    - BUILD_MAKEPATH=build BUILD_MAKEARGS=distcheck

matrix:
    allow_failures:
    exclude:
        - os: osx
          compiler: gcc
